### ISSUE TITLE
[FEAT] 홈 화면 UI 구성

### ISSUE THREAD

**Issue by EunHee-Jeong** [SOPT-29th-Joint-Seminar-10/Client-iOS#12]
## 📌  Feature Issue

홈 탭바 부분 → 차량 플랜 화면의 UI를 구성하는 이슈 입니다

## 📝  To-do

- [x] 전체적인 화면 - 스크롤 뷰 만들기
- [x] 예약일 입력 - 텍스트 필드, 버튼 추가하기
- [x] 대여 목록 - 스택 뷰 구성하기
- [x] 추천 차량 - 컬렉션 뷰 구성하기
- [x] 추천 차량 커스텀뷰 연결
