### ISSUE TITLE
[FEAT] 필터 화면 UI 구성

### ISSUE THREAD

**Issue by beansbin** [SOPT-29th-Joint-Seminar-10/Client-iOS#14]
## 📌  Feature Issue
필터 화면 UI 구성

## 📝  To-do

- [x] FilterVC 생성
- [x] 상단 UI  구성 및 오토레이아웃
- [x] 필터 컬렉션뷰 생성 및 오토레이아웃
- [x] 차량 표시 컬렉션뷰 생성 및 오토레이아웃
- [x] filterCVC 생성
