### ISSUE TITLE
[FEAT] 네비게이션바 커스텀 및 FilterVC 컬렉션뷰 UI 수정

### ISSUE THREAD

**Issue by beansbin** [SOPT-29th-Joint-Seminar-10/Client-iOS#24]
## 📌  Feature Issue

네비게이션바 커스텀 및 FilterCV 컬렉션뷰 UI 수정

## 📝  To-do

- [x] 네비게이션바 커스텀
- [x] FilterVC 네비게이션 아이템 설정
- [x] FilterVC 필터 컬렉션뷰 오토레이아웃 수정
- [x] 컬렉션뷰 그림자 반영
