### ISSUE TITLE
[FEAT] 예약목록 스택뷰와 부분 수정

### ISSUE THREAD

**Issue by EunHee-Jeong** [SOPT-29th-Joint-Seminar-10/Client-iOS#27]
## 📌  Feature Issue

스택뷰 구성하기 / 컬렉션뷰 셀 끝까지 보이도록 수정하기

## 📝  To-do

- [x] 컬렉션뷰 오류 수정하기
- [x] 스택뷰 정적으로 구성하기
- [ ] 스택뷰 동적으로 구성하기 (바꾸기)
