### ISSUE TITLE
[FEAT] 차량 필터 리스트 API 연결

### ISSUE THREAD

**Issue by beansbin** [SOPT-29th-Joint-Seminar-10/Client-iOS#31]
## 📌  Feature Issue

차량 필터 리스트 API 연결

## 📝  To-do

- [x] 필터 분기 처리 로직
- [x] 예약 차 목록 컬렉션뷰 데이터 넣기
- [x] 필터 컬렉션뷰 초기화 동작
- [x] 차량 필터 리스트 API 연결
- [x] 날짜 받아오기
