### ISSUE TITLE
[Improve] 필터 API 연결 코드 리팩토링

### ISSUE THREAD

**Issue by beansbin** [SOPT-29th-Joint-Seminar-10/Client-iOS#39]
## 📌  Feature Issue

필터 API 연결 코드 리팩토링

## 📝  To-do

- [x] FilterResponseData 주석 수정
- [x] kingfisher 라이브러리 사용하기
- [x] 필터 로직 구조 수정
